### ISSUE TITLE
Publish non-snapshot version to Clojars

### ISSUE THREAD

**Issue by r0man** [rm-hull/inkspot#6]
Hi Richard,

would you mind publishing a non SNAPSHOT version to Clojars? I'm
using this library and have to export LEIN_SNAPSHOTS_IN_RELEASE
whenever I make a release (via lein release) of my own stuff.

Thanks, Roman.

**Comment by rm-hull** [comment]
Hi - pushed current code as 0.1.0 to https://clojars.org/rm-hull/inkspot - will probably push out a 0.2.0 as well with latest dependencies.

**Comment by r0man** [comment]
Cool, thank you! :)
